import NavBar from "@/components/NavBar";
import "./globals.css";
import { AuthProvider } from "@/context/authContext";
import ProtectedRouter from "@/components/ProtectedRouter";
import EmergentNotificacion from "@/components/EmergentNotification";
import { Emergent_NotifiProvider } from "@/context/notifiContext";
import { RouterProvider } from "@/components/RouterProvider";
import GlobalLoader from "@/components/GlobalLoader";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Emergent_NotifiProvider>
            <RouterProvider>
              <NavBar />
              <GlobalLoader>
                <EmergentNotificacion />
                <ProtectedRouter>{children}</ProtectedRouter>
              </GlobalLoader>
            </RouterProvider>
          </Emergent_NotifiProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
